name: general_date_format
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/ali-you
repository: https://github.com/ali-you/general-date-format-package
documentation: https://github.com/ali-you/general-date-format-package
issue_tracker: https://github.com/ali-you/general-date-format-package/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  general_datetime: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
