name: general_date_format
description: "A Dart/Flutter package to format dates in a flexible and generalized way, extending the functionality of the general_datetime package for versatile date formatting."
version: 0.1.2
homepage: https://github.com/ali-you
repository: https://github.com/ali-you/general-date-format-package
documentation: https://github.com/ali-you/general-date-format-package
issue_tracker: https://github.com/ali-you/general-date-format-package/issues
topics:
  - date
  - time
  - format
  - utils
  - service

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  general_datetime: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
