"""Generate the Afrikaans correction from Unicode CLDR 48 (stdlib only).

Other Persian calendar names retain their legacy translations. Weekday, time,
quarter and week metadata come from intl at runtime, for all three calendars.
"""
import argparse
import hashlib
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ("https://raw.githubusercontent.com/unicode-org/cldr-json/48.0.0/"
          "cldr-json/cldr-cal-persian-full/main/af/ca-persian.json")
CACHE = ROOT / ".dart_tool/cldr-48/persian-af.json"
OUTPUT = ROOT / "packages/general_date_format_core/lib/src/symbols/persian_af_calendar_data.dart"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Verify generated output without modifying it")
    args = parser.parse_args()
    if not CACHE.exists():
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        request = urllib.request.Request(SOURCE, headers={"User-Agent": "general-date-format-generator"})
        with urllib.request.urlopen(request, timeout=45) as response:
            CACHE.write_bytes(response.read())
    raw = CACHE.read_bytes()
    data = json.loads(raw)["main"]["af"]["dates"]["calendars"]["persian"]
    values = {}
    for key, context, width in [
        ("MONTHS", "format", "wide"),
        ("SHORTMONTHS", "format", "abbreviated"),
        ("NARROWMONTHS", "format", "narrow"),
        ("STANDALONEMONTHS", "stand-alone", "wide"),
        ("STANDALONESHORTMONTHS", "stand-alone", "abbreviated"),
        ("STANDALONENARROWMONTHS", "stand-alone", "narrow"),
    ]:
        values[key] = [data["months"][context][width][str(i)] for i in range(1, 13)]
    for key, field in [("ERAS", "eraAbbr"), ("ERANAMES", "eraNames")]:
        values[key] = [data["eras"][field]["0"]] * 2

    def dart(value):
        return json.dumps(value, ensure_ascii=False).replace("$", "\\$")

    lines = ["// Generated by tool/generate_persian_af_symbols.py; Unicode CLDR 48.",
             f"// Source: {SOURCE}",
             f"// SHA-256: {hashlib.sha256(raw).hexdigest()}",
             "// See THIRD_PARTY_NOTICES.md for the Unicode license.",
             "const persianAfCalendarData = <String, List<String>>{"]
    for key, value in values.items():
        if len(value) == 2:
            lines.append(f"  {dart(key)}: {dart(value)},")
        else:
            lines.append(f"  {dart(key)}: [")
            lines.extend("    " + dart(item) + ("," if i < len(value) - 1 else "")
                         for i, item in enumerate(value))
            lines.append("  ],")
    lines.extend(["};", ""])
    content = "\n".join(lines)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Persian Afrikaans symbols need regeneration")
    else:
        OUTPUT.write_text(content, encoding="utf-8")
    print("Persian Afrikaans symbols verified" if args.check else "Generated Persian Afrikaans symbols")


if __name__ == "__main__":
    main()
