"""Generate Hijri names from pinned Unicode CLDR 48 data (stdlib only)."""
import concurrent.futures
import json
from pathlib import Path
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://raw.githubusercontent.com/unicode-org/cldr-json/48.0.0/"
CACHE = ROOT / ".dart_tool" / "cldr-48"
CACHE.mkdir(parents=True, exist_ok=True)


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "general-date-format-generator"})
    with urllib.request.urlopen(request, timeout=45) as response:
        return response.read()


def main():
    locales = re.findall(r'"([^"]+)"', (ROOT / "lib/src/common/symbol_list.dart").read_text())
    index = CACHE / "locales.json"
    if not index.exists():
        index.write_bytes(fetch("https://api.github.com/repos/unicode-org/cldr-json/contents/"
                                "cldr-json/cldr-cal-islamic-full/main?ref=48.0.0"))
    available = {item["name"] for item in json.loads(index.read_bytes())}
    aliases = {"en_ISO": "en", "in": "id", "iw": "he", "tl": "fil", "no": "nb",
               "no_NO": "nb", "zh_CN": "zh", "zh_TW": "zh-Hant", "zh_HK": "zh-Hant-HK"}
    sources = {}
    for locale in locales:
        candidate = aliases.get(locale, locale.replace("_", "-"))
        while candidate not in available and "-" in candidate:
            candidate = candidate.rsplit("-", 1)[0]
        if candidate not in available:
            raise ValueError(f"No CLDR locale for {locale}: {candidate}")
        sources[locale] = candidate

    def calendar(locale):
        path = CACHE / f"{locale}.json"
        if not path.exists():
            path.write_bytes(fetch(BASE + "cldr-json/cldr-cal-islamic-full/main/" +
                                   locale + "/ca-islamic-umalqura.json"))
        return json.loads(path.read_bytes())["main"][locale]["dates"]["calendars"]["islamic-umalqura"]

    with concurrent.futures.ThreadPoolExecutor(max_workers=12) as pool:
        calendars = dict(zip(sorted(set(sources.values())),
                            pool.map(calendar, sorted(set(sources.values())))))

    def dart(value):
        return json.dumps(value, ensure_ascii=False).replace("$", "\\$")

    text = ["// Generated by tool/generate_hijri_symbols.py from Unicode CLDR 48.",
            "// Source: unicode-org/cldr-json, tag 48.0.0, ca-islamic-umalqura.json.",
            "// See THIRD_PARTY_NOTICES.md for the Unicode license.",
            "const hijriCalendarData = <String, Map<String, List<String>>>{"]
    for locale in locales:
        data = calendars[sources[locale]]
        values = {}
        for key, context, width in [
                ("MONTHS", "format", "wide"),
                ("SHORTMONTHS", "format", "abbreviated"),
                ("NARROWMONTHS", "format", "narrow"),
                ("STANDALONEMONTHS", "stand-alone", "wide"),
                ("STANDALONESHORTMONTHS", "stand-alone", "abbreviated"),
                ("STANDALONENARROWMONTHS", "stand-alone", "narrow")]:
            values[key] = [data["months"][context][width][str(i)] for i in range(1, 13)]
        for key, cldr_key in [("ERAS", "eraAbbr"), ("ERANAMES", "eraNames")]:
            era = data["eras"][cldr_key]["0"]
            values[key] = [era, era]
        text.append(f"  {dart(locale)}: {{ // CLDR {sources[locale]}")
        text.extend(f"    {dart(key)}: {dart(value)}," for key, value in values.items())
        text.append("  },")
    text.append("};\n")
    (ROOT / "lib/src/symbols/hijri_calendar_data.dart").write_text("\n".join(text), encoding="utf-8")
    license_path = ROOT / "THIRD_PARTY_NOTICES.md"
    license_path.write_text("# Third-party data\n\nThe generated Hijri month and era names are derived from "
                           "[Unicode CLDR 48](https://github.com/unicode-org/cldr-json/tree/48.0.0/"
                           "cldr-json/cldr-cal-islamic-full). Regional and legacy locale aliases are "
                           "recorded in the generator and generated table.\n\n" +
                           fetch(BASE + "LICENSE").decode("utf-8"), encoding="utf-8")
    print(f"Generated {len(locales)} locales from {len(calendars)} CLDR locales.")


if __name__ == "__main__":
    main()
