// Generated by tool/generate_persian_af_symbols.py; Unicode CLDR 48.
// Source: https://raw.githubusercontent.com/unicode-org/cldr-json/48.0.0/cldr-json/cldr-cal-persian-full/main/af/ca-persian.json
// SHA-256: af2aef229e0cd3b8829bd584d9d2100042693ba726f568d0d37789a0c9a9930d
// See THIRD_PARTY_NOTICES.md for the Unicode license.
const persianAfCalendarData = <String, List<String>>{
  "MONTHS": [
    "Farvardin",
    "Ordibehesht",
    "Khordad",
    "Tir",
    "Mordad",
    "Shahrivar",
    "Mehr",
    "Aban",
    "Azar",
    "Dey",
    "Bahman",
    "Esfand"
  ],
  "SHORTMONTHS": [
    "Farvardin",
    "Ordibehesht",
    "Khordad",
    "Tir",
    "Mordad",
    "Shahrivar",
    "Mehr",
    "Aban",
    "Azar",
    "Dey",
    "Bahman",
    "Esfand"
  ],
  "NARROWMONTHS": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12"
  ],
  "STANDALONEMONTHS": [
    "Farvardin",
    "Ordibehesht",
    "Khordad",
    "Tir",
    "Mordad",
    "Shahrivar",
    "Mehr",
    "Aban",
    "Azar",
    "Dey",
    "Bahman",
    "Esfand"
  ],
  "STANDALONESHORTMONTHS": [
    "Farvardin",
    "Ordibehesht",
    "Khordad",
    "Tir",
    "Mordad",
    "Shahrivar",
    "Mehr",
    "Aban",
    "Azar",
    "Dey",
    "Bahman",
    "Esfand"
  ],
  "STANDALONENARROWMONTHS": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12"
  ],
  "ERAS": ["AP", "AP"],
  "ERANAMES": ["AP", "AP"],
};
